name: Deploy to EC2 Web Server ABC Client

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          

      - name: Deploy code to EC2
        run: |
          rsync -r --delete-after --quiet $GITHUB_WORKSPACE/ user@${{ secrets.EC2_HOST }}:/path/to/destination
